name: Sharkey.dart CI
on: [push]
env:
  BLAHAJ_API_TOKEN: ${{ secrets.BLAHAJ_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: "Install dependencies."
        run: dart pub get
      - name: "Test routines."
        run: dart test --chain-stack-traces
